<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>

</body>

</html>
<script src="./jquery-3.3.1.js"></script>
<script>
    // $.ajax({
    //     url:'./data.json',
    //     success:function(){
    //         $.ajax({
    //             url:'./data.json',
    //             success:function(){

    //             }
    //         })
    //     }
    // })

    //promise 实例有三个状态分别是  pending  resolved  rejected
    //pending  代表当前的promise 处于等待状态
    //resolved 执行成功的回调函数
    //rejected 执行失败的回调函数
    //状态一经修改  就不会再发生改变
    // let p = new Promise(function (resolve, reject) {
    //     //resolve 执行成功的回调函数
    //     //reject 执行失败的回调函数
    //     //具体执行成功还是失败有书写者决定
    //     setTimeout(() => {
    //         reject(123)
    //         // resolve(123)
    //     }, 3000)
    //     resolve(qqq)

    // })

    // then 接受两个函数作为参数  第一个函数对应 resolv  第二个函数对应 reject
    // p.then(function (data) {
    //     console.log('success')
    //     console.log(data);
    // }, function (err) {
    //     console.log('error')
    //     console.log(err);
    //     console.log(aaa);
    // }).then(function (data2) {
    //     console.log('data2', data2)
    // }, function (err2) {
    //     console.log('err2', err2)
    // })

    // let p = new Promise(function(res,rej){
    //     $.ajax({
    //         url:'./data.json',
    //         success:res,
    //         error:function(data){
    //             rej(data)
    //         }

    //     })
    // })
    // p.then(function(data){
    //     //then 可以写两个参数  也可以写一个参数  
    //     //写一个参数给对应的是成功的回调  失败信息有 catch 捕获
    //     console.log(data)
    //     return new Promise(function(res,rej){
    //         res(666)
    //     })
    // }).then(function(data2){
    //     console.log(data2)
    // }).catch(function(err){
    //     console.log(err)
    // })

    new Promise(function(res,rej){
        rej(123)
        console.log(666)
    }).then((data)=>{
        console.log(data)
    }).catch((err)=>{
        console.log(err)
        return 1111
    }).finally(()=>{
        console.log()
    })
    console.log(69999)
</script>